-- Teman Digital AI Office — database foundation reference
--
-- Live project:
-- wsewvhsnvgtksrhutsuw
--
-- Public entities:
-- profiles, clients, leads, products, orders, licenses, projects, project_tasks,
-- revisions, transactions, invoices, ai_agents, ai_tasks, ai_handoffs, approvals,
-- knowledge_documents, activity_logs, notifications.
--
-- Security:
-- - RLS enabled on all public tables.
-- - anon has no table access.
-- - authenticated uses explicit Data API grants constrained by RLS.
-- - AI Developer and owner-only AI tasks are protected by backend policies.
--
-- Applied migrations:
-- 20261004065419 foundation_core_schema
-- 20261004065551 optimize_notification_rls
-- 20261004072134 cover_foreign_key_indexes
--
-- The complete applied SQL is tracked under supabase/migrations/.
-- Destructive rollback scripts remain manual and require explicit owner approval.
