-- Migration manifest for the already-applied live migration:
-- version: 20261004065419
-- name: foundation_core_schema
-- project: wsewvhsnvgtksrhutsuw
--
-- The live migration was applied through the Supabase Migration API and is
-- recorded in Supabase migration history. This repository file intentionally
-- acts as a manifest until the live schema is pulled/exported into a complete
-- reproducible SQL migration.
--
-- IMPORTANT:
-- Do not run a hand-written replacement against production.
-- Use Supabase migration history + schema pull/export before provisioning
-- another environment.
--
-- Manual destructive rollback is documented separately under supabase/rollback/
-- and requires explicit owner approval.
